In [1]:
import time
import os
import pandas as pd
from pcap_parse import *

In [2]:
normal_dir = "D:\\Notebooks\\Datasets\\Network_dataset_pcaps\\normal_pcaps"
mal_dir = "D:\\Notebooks\\Datasets\\Network_dataset_pcaps\\normal_attack_pcaps"
truth_dir = "D:\\Notebooks\\Datasets\\truth"

In [3]:
files = os.listdir(truth_dir)
truth_df = pd.DataFrame()
for dataset in files:
    cur = pd.read_csv(truth_dir+"\\"+dataset)
    truth_df = pd.concat([truth_df, cur], axis=0)

In [4]:
truth_df.head()

           ts        src_ip  src_port         dst_ip  dst_port proto      type
0  1556021522  192.168.1.31     38140   192.168.1.49      1185   tcp  scanning
1  1556021522  192.168.1.31     50945  192.168.1.186      5815   tcp  scanning
2  1556021522  192.168.1.31     50945  192.168.1.250      3011   tcp  scanning
3  1556021522  192.168.1.31     50946   192.168.1.49     32775   tcp  scanning
4  1556021522  192.168.1.31     50950  192.168.1.133      1000   tcp  scanning

In [5]:
df = pd.DataFrame(columns=["p_bytes","label","ts","src_ip","dst_ip","src_port","dst_port","pcap_ver"])
#df = parse_pcap(normal_dir+"\\normal_IoT_2.pcap", df, 0)
#df = parse_pcap(mal_dir+"\\normal_scanning\\normal_scanning1.pcap", df, 0)
for file_name in os.listdir(mal_dir+"\\normal_scanning"):    
    df = parse_pcap(mal_dir+"\\normal_scanning\\"+file_name, df, 1)

Using v2.4
Using v2.4
Using v2.4
Using v2.4
Using v2.4
Using v1.0

In [6]:
df.head()

,p_bytes,label,ts,src_ip,dst_ip,src_port,dst_port,pcap_ver
0,b'\x00\x03\x00\x01\x00\x06\x00\x0c)[s[\x00\x00...,1,1556021410,192.168.1.30,192.168.1.49,49508,9050,2
1,"b""\x00\x03\x00\x01\x00\x06\x00\x0c)[s[\x00\x00...",1,1556021410,192.168.1.30,192.168.1.46,50567,1002,2
2,b'\x00\x03\x00\x01\x00\x06\x00\x0c)[s[\x00\x00...,1,1556021410,192.168.1.30,192.168.1.169,50567,1106,2
3,b'\x00\x03\x00\x01\x00\x06\x00\x0c)\xb8\xb1t\x...,1,1556021410,192.168.1.31,192.168.1.49,58550,2718,2
4,b'\x00\x03\x00\x01\x00\x06\x00\x0c)\xb8\xb1t\x...,1,1556021410,192.168.1.31,192.168.1.133,38138,10566,2

In [9]:
df['src_ip'] = df['src_ip'].astype(str)

In [10]:
len(df)

30226049

In [13]:
df[ (df["ts"]==1556021522) & (df["src_ip"]=="192.168.1.31") ]

,p_bytes,label,ts,src_ip,dst_ip,src_port,dst_port,pcap_ver
9031,b'\x00\x03\x00\x01\x00\x06\x00\x0c)\xb8\xb1t\x...,1,1556021522,192.168.1.31,192.168.1.133,35795,636,2
9080,b'\x00\x03\x00\x01\x00\x06\x00\x0c)\xb8\xb1t\x...,1,1556021522,192.168.1.31,192.168.1.133,38138,10621,2
9091,b'\x00\x03\x00\x01\x00\x06\x00\x0c)\xb8\xb1t\x...,1,1556021522,192.168.1.31,192.168.1.49,54805,1051,2
9106,b'\x00\x03\x00\x01\x00\x06\x00\x0c)\xb8\xb1t\x...,1,1556021522,192.168.1.31,192.168.1.49,50946,32775,2
9130,b'\x00\x03\x00\x01\x00\x06\x00\x0c)\xb8\xb1t\x...,1,1556021522,192.168.1.31,192.168.1.133,50950,1000,2
9132,b'\x00\x03\x00\x01\x00\x06\x00\x0c)\xb8\xb1t\x...,1,1556021522,192.168.1.31,192.168.1.250,50945,3011,2
9147,b'\x00\x03\x00\x01\x00\x06\x00\x0c)\xb8\xb1t\x...,1,1556021522,192.168.1.31,192.168.1.49,38140,1185,2
9148,b'\x00\x03\x00\x01\x00\x06\x00\x0c)\xb8\xb1t\x...,1,1556021522,192.168.1.31,192.168.1.186,50945,5815,2

In [14]:
df[ (df["ts"]==1556021522) & (df["src_ip"]=="192.168.1.32") ]

,p_bytes,label,ts,src_ip,dst_ip,src_port,dst_port,pcap_ver
9022,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.152,53998,587,2
9023,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.46,53922,8500,2
9027,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.79,53921,1600,2
9028,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.103,53921,49157,2
9030,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.169,53921,7496,2
9038,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.169,53922,7496,2
9039,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.46,53922,1213,2
9040,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.46,53922,873,2
9059,"b""\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...",1,1556021522,192.168.1.32,192.168.1.250,61322,25,2
9068,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.49,35484,4,2
9118,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.49,61179,9090,2
9119,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.133,61181,3221,2
9134,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.133,35484,1122,2
9150,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.49,54773,18988,2
9151,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.133,54774,146,2
9154,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.186,61172,8222,2

In [14]:
df[ (df["ts"]==1556021522) ]['src_ip'].value_counts()

192.168.1.30     72
192.168.1.32      9
192.168.1.31      6
192.168.1.250     6
192.168.1.195     2
192.168.1.152     2
192.168.1.180     2
192.168.1.6       1
Name: src_ip, dtype: int64

In [15]:
truth_df[truth_df['ts']==1556021522]['src_ip'].value_counts()

192.168.1.30    79
192.168.1.32    16
192.168.1.31     8
Name: src_ip, dtype: int64

In [15]:
truth_df[truth_df['ts']==1556021522]

,ts,src_ip,src_port,dst_ip,dst_port,proto,type
0,1556021522,192.168.1.31,38140,192.168.1.49,1185,tcp,scanning
1,1556021522,192.168.1.31,50945,192.168.1.186,5815,tcp,scanning
2,1556021522,192.168.1.31,50945,192.168.1.250,3011,tcp,scanning
3,1556021522,192.168.1.31,50946,192.168.1.49,32775,tcp,scanning
4,1556021522,192.168.1.31,50950,192.168.1.133,1000,tcp,scanning
...,...,...,...,...,...,...,...
33268,1556021522,192.168.1.30,62947,192.168.1.186,9101,tcp,scanning
33269,1556021522,192.168.1.30,62947,192.168.1.186,9876,tcp,scanning
33270,1556021522,192.168.1.30,62951,192.168.1.49,5550,tcp,scanning
33271,1556021522,192.168.1.31,35795,192.168.1.133,636,tcp,scanning
33272,1556021522,192.168.1.31,38138,192.168.1.133,10621,tcp,scanning

In [16]:
df[(df["ts"]==1556021522)]#['src_port'].value_counts()

,p_bytes,label,ts,src_ip,dst_ip,src_port,dst_port,pcap_ver
9021,b'\x00\x03\x00\x01\x00\x06\x00\x0c)[s[\x00\x00...,1,1556021522,192.168.1.30,192.168.1.186,62947,3827,2
9022,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.152,53998,587,2
9023,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.46,53922,8500,2
9024,b'\x00\x03\x00\x01\x00\x06\x00\x0c)[s[\x00\x00...,1,1556021522,192.168.1.30,192.168.1.186,62947,366,2
9025,b'\x00\x03\x00\x01\x00\x06\x00\x0c)[s[\x00\x00...,1,1556021522,192.168.1.30,192.168.1.186,62946,3005,2
...,...,...,...,...,...,...,...,...
9151,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.133,54774,146,2
9152,b'\x00\x03\x00\x01\x00\x06\x00\x0c)[s[\x00\x00...,1,1556021522,192.168.1.30,192.168.1.186,62947,3889,2
9153,b'\x00\x03\x00\x01\x00\x06\x00\x0c)[s[\x00\x00...,1,1556021522,192.168.1.30,192.168.1.186,62947,5222,2
9154,b'\x00\x03\x00\x01\x00\x06\x00\x0c)HBL\x00\x00...,1,1556021522,192.168.1.32,192.168.1.186,61172,8222,2
9155,b'\x00\x03\x00\x01\x00\x06\x00\x0c)[s[\x00\x00...,1,1556021522,192.168.1.30,192.168.1.186,62946,5544,2

In [26]:
sorted(df[(df["ts"]==1556021522) & (df["src_port"]==62946)]['dst_port'].unique())

[119,
 873,
 903,
 1064,
 1067,
 1074,
 1097,
 1666,
 1972,
 2043,
 2045,
 2047,
 2608,
 3005,
 3809,
 3889,
 3971,
 4129,
 5051,
 5222,
 5544,
 5730,
 5810,
 5901,
 5904,
 6002,
 6059,
 7937,
 8042,
 9010,
 9101,
 10025,
 10566,
 20005,
 20222,
 32770,
 32781,
 34571,
 51103,
 54045]

In [25]:
sorted(truth_df[(truth_df["ts"]==1556021522) & (truth_df["src_port"]==62946)]['dst_port'].unique())

[119,
 873,
 903,
 1064,
 1067,
 1074,
 1097,
 1666,
 1972,
 2043,
 2045,
 2047,
 2608,
 3005,
 3809,
 3889,
 3971,
 4129,
 5051,
 5222,
 5544,
 5730,
 5810,
 5901,
 5904,
 6002,
 6059,
 7937,
 8042,
 9010,
 9101,
 10025,
 10566,
 20005,
 20222,
 32770,
 32781,
 34571,
 51103,
 54045]

In [39]:
df[(df['pcap_ver']==1) & (df['timestamp']==1556086286)]['src_ip'].value_counts()

192.168.1.30       646
192.168.1.32       270
192.168.1.31       117
192.168.1.194       33
192.168.1.169        9
192.168.1.193        7
192.168.1.190        7
192.168.1.28         4
115.91.192.168       3
192.168.1.195        3
66.76.192.168        3
177.116.192.168      2
Name: src_ip, dtype: int64

In [40]:
truth_df[truth_df['ts']==1556086286]['src_ip'].value_counts()

192.168.1.30     639
192.168.1.32     267
192.168.1.31      80
192.168.1.169      1
Name: src_ip, dtype: int64

In [11]:
# Figuring out converting to 32bit ints to 64 bit int
ts1 = int.from_bytes(df[df['pcap_ver']==1]['timestamp'][26966366][0:4], "little")
ts2 = int.from_bytes(df[df['pcap_ver']==1]['timestamp'][26966366][4:8], "little")
temp = ts1 << 32
temp = temp | ts2

TypeError: 'int' object is not subscriptable

In [17]:
round(1556086285972169/1000000)

1556086286

In [5]:
# Read in normal traffic data
i = 1
for file_name in os.listdir(normal_dir):
    print(str(i)+"/"+str(len(os.listdir(normal_dir))), end=" : ")
    df = parse_pcap(normal_dir+"\\"+file_name, df, 0)
    i += 1

1/15 : Using v1.0
2/15 : Using v1.0
3/15 : Using v1.0
4/15 : Using v1.0
5/15 : Using v1.0
6/15 : Using v1.0

KeyboardInterrupt:

In [9]:
print(len(df))
df.to_pickle('D:\\Notebooks\\Datasets\\raw_normal.pkl')

31287179

In [11]:
# Read in malicious data
for folder in os.listdir(mal_dir):
    df = pd.DataFrame(columns=["p_bytes","from_ip","timestamp"])
    i = 1
    print(folder)
    for file_name in os.listdir(mal_dir+"\\"+folder):    
        print(str(i)+"/"+str(len(os.listdir(mal_dir+"\\"+folder))), end=" : ")
        df = parse_pcap(mal_dir+"\\"+folder+"\\"+file_name, df, 1)
        i += 1
    #print(len(df))
    df.to_pickle('D:\\Notebooks\\Datasets\\raw_'+folder+'.pkl')

Injection_normal
1/4 : Using v2.4
2/4 : Using v1.0
3/4 : Using v1.0
4/4 : Using v2.4
MITM_normal
1/4 : Using v2.4
2/4 : Using v2.4
3/4 : Using v2.4
4/4 : Using v2.4
normal_backdoor
1/1 : Using v1.0
normal_DDoS
1/12 : Using v2.4
2/12 : Using v1.0
3/12 : Using v1.0
4/12 : Using v1.0
5/12 : Using v2.4
6/12 : Using v1.0
7/12 : Using v1.0
8/12 : Using v1.0
9/12 : Using v1.0
10/12 : Using v1.0
11/12 : Using v1.0
12/12 : Using v1.0
normal_DoS
1/5 : Using v2.4
2/5 : Using v1.0
3/5 : Using v1.0
4/5 : Using v1.0
5/5 : Using v1.0
normal_runsomware
1/2 : Using v1.0
2/2 : Using v1.0
normal_scanning
1/6 : Using v2.4
2/6 : Using v2.4
3/6 : Using v2.4
4/6 : Using v2.4
5/6 : Using v2.4
6/6 : Using v1.0
normal_XSS
1/10 : Using v2.4
2/10 : Using v1.0
3/10 : Using v2.4
4/10 : Using v1.0
5/10 : Using v1.0
6/10 : Using v1.0
7/10 : Using v1.0
8/10 : Using v1.0
9/10 : Using v1.0
10/10 : Using v1.0
password_normal
1/5 : Using v2.4
2/5 : Using v1.0
3/5 : Using v1.0
4/5 : Using v1.0
5/5 : Using v1.0

In [12]:
del(df)

In [16]:
temp = pd.DataFrame(columns=["p_bytes"])
#temp = parse_pcap(normal_dir+"\\normal_13.pcap", temp, 0)
#temp = parse_pcap(normal_dir+"\\normal_IoT_2.pcap", temp, 0)
temp = parse_pcap(normal_dir+"\\normal_IoT_3.pcap", temp, 0)

Using v2.4

In [17]:
len(temp)

2728861

In [ ]:
scanning      7140161
ddos          6165008
dos           3375328
xss           2108944
password      1365958
normal         788599
backdoor       508116
injection      452659
ransomware      72805
mitm             1052

In [3]:
# Create mixed dataset
normal = pd.read_pickle("D:\\Notebooks\\Datasets\\raw_normal.pkl")

In [4]:
len(normal)

31287179